### ISSUE TITLE
CSS3 Comma Delimited Values

### ISSUE THREAD

**Issue by svjoshua** [simpleviewinc/code-guide#1]
Hey Folks,

In CSS3 several properties support a comma separated list of values. Our current code guide doesn't address this specifically so I thought it might be good to talk about it. Given the potential length of a valid value string, it would seem most inline with our other style rules to split each value out on a new line with the comma at the end of the previous line and the values all starting at the same tab space.

.div{
	background-image:	http://longcloudinaryurl-1.ext,
						http://longcloudinaryurl-2.ext,
						http://longcloudinaryurl-3.ext;
}

However, for items like transition, it may be overkill for each value to live on its own line.

.div{
	transition:	color .5s,
				background .5s;
}

**Comment by arkmuntasser** [comment]
@svjoshua ,

This is actually addressed in the code guide: https://simpleviewinc.github.io/code-guide/#css-syntax bullet 8.

> Comma-separated property values should include a space after each comma (e.g., box-shadow).

```
.selector {
    box-shadow: 0 1px 2px #ccc, inset 0 1px 0 #fff;
}
```

We landed on simply keeping everything on a single line with a space following the comma.

While I agree with your example with `background-image` potentially getting too long, I don't know that it comes up often enough to make a new rule for it.

That said, I'll discuss it with the others and get back to you.

Thank you

**Comment by svjoshua** [comment]
Drat, missed that line.

**Comment by arkmuntasser** [comment]
@svjoshua 

We discussed it and for now we'll not be adding a new rule for the case of long comma separated lists. However, if it becomes a regular thing, then we can revisit it at that time.

Thank you
